---

- include_role:
    name: almaops.pkg_install
  vars:
    pkg_install_packages: "{{ ['docker.io'] + (docker_enable_docker_compose | ternary(['docker-compose'], [])) }}"
  when:
    - docker_enable_pkg_install
    - ansible_distribution | default(undef(hint="you must gather facts before running this role")) in [ 'Ubuntu', 'Debian' ]

- name: "{{ docker_task_prefix }} enable Loki plugin"
  community.docker.docker_plugin:
    plugin_name: "grafana/loki-docker-driver:{{ docker_log_driver_loki_version }}"
    alias: loki
    state: enable
  when:
    - docker_log_driver == "loki"

- include_role:
    name: almaops.pip_install
  vars:
    pip_install_packages:
      - docker
  when:
    - docker_enable_pip_install

- include_tasks: configure-dockerd.yml
  when:
    - docker_enable_configure

- include_tasks: docker-login.yml
  loop: "{{ docker_registry_credentials }}"
  loop_control:
    loop_var: creds
...
